// McArthur Engineering — contact book.
//
// DEMONSTRATION DATA. Every business record below is invented for the walkthrough:
// fictional firms, 555 phone numbers and example.com addresses, all reserved for
// exactly this purpose so nothing here can be mistaken for a real company or dialed
// by accident. The only real entries are the public agency counters at the top —
// county, city, highway district, health district and the state — because a walkthrough
// of a Kootenai engineering firm should show the counters it actually deals with.
//
// Sep 13 2026: this replaced a real one-thousand-and-fifty-one-record prospect list
// sourced from the AE master book. That list was sitting in a public file on an
// unsigned proposal site, readable by anyone who asked for it by name. A demo does
// not need a real book to prove the room works.
window.MCA_CONTACTS=[
{
"n": "Kootenai County — Community Development",
"v": "Government · County",
"c": "Coeur d'Alene",
"st": "ID",
"p": "",
"w": "https://www.kcgov.us",
"e": "",
"f": "",
"note": "Plats, zoning and building permits — the county counter.",
"k": "Government",
"kc": 1
},
{
"n": "Kootenai County — Assessor",
"v": "Government · County",
"c": "Coeur d'Alene",
"st": "ID",
"p": "",
"w": "https://www.kcgov.us",
"e": "",
"f": "",
"note": "Parcel records and ownership.",
"k": "Government",
"kc": 1
},
{
"n": "City of Post Falls — Engineering",
"v": "Government · City",
"c": "Post Falls",
"st": "ID",
"p": "",
"w": "https://www.postfallsidaho.org",
"e": "",
"f": "",
"note": "Right-of-way, grading and city standards.",
"k": "Government",
"kc": 1
},
{
"n": "City of Rathdrum — Public Works",
"v": "Government · City",
"c": "Rathdrum",
"st": "ID",
"p": "",
"w": "https://www.rathdrum.org",
"e": "",
"f": "",
"note": "Water, sewer and street approvals.",
"k": "Government",
"kc": 1
},
{
"n": "East Side Highway District",
"v": "Government · Highway District",
"c": "Coeur d'Alene",
"st": "ID",
"p": "",
"w": "https://www.eastsidehighwaydistrict.com",
"e": "",
"f": "",
"note": "Approach permits and road standards.",
"k": "Government",
"kc": 1
},
{
"n": "Panhandle Health District",
"v": "Government · Health District",
"c": "Hayden",
"st": "ID",
"p": "",
"w": "https://panhandlehealthdistrict.org",
"e": "",
"f": "",
"note": "Septic and well permitting.",
"k": "Government",
"kc": 1
},
{
"n": "Idaho Transportation Department — District 1",
"v": "Government · State",
"c": "Coeur d'Alene",
"st": "ID",
"p": "",
"w": "https://itd.idaho.gov",
"e": "",
"f": "",
"note": "State highway approaches and encroachment permits.",
"k": "Government",
"kc": 1
},
{
"n": "Silver Lake Architects",
"v": "Architecture",
"c": "Coeur d'Alene",
"st": "ID",
"p": "(208) 555-1000",
"w": "https://www.example.com/silverlakearchitec",
"e": "info@silverlakearchitec.example.com",
"f": "",
"note": "Design partner on two mixed-use shells. Sends structural out.",
"k": "Business",
"kc": 1
},
{
"n": "Ridgeline Design Studio",
"v": "Architecture",
"c": "Sandpoint",
"st": "ID",
"p": "(208) 555-1007",
"w": "https://www.example.com/ridgelinedesignstu",
"e": "info@ridgelinedesignstu.example.com",
"f": "",
"note": "Residential and small commercial. No in-house structural.",
"k": "Business",
"kc": 1
},
{
"n": "Cedar & Stone Architecture",
"v": "Architecture",
"c": "Spokane",
"st": "WA",
"p": "(208) 555-1014",
"w": "https://www.example.com/cedarandstonearchi",
"e": "info@cedarandstonearchi.example.com",
"f": "",
"note": "Cross-border work. Asks for Idaho-stamped drawings.",
"k": "Business",
"kc": 1
},
{
"n": "Fernan Ridge Builders",
"v": "General Contractor",
"c": "Coeur d'Alene",
"st": "ID",
"p": "(208) 555-1021",
"w": "https://www.example.com/fernanridgebuilder",
"e": "info@fernanridgebuilder.example.com",
"f": "",
"note": "Design-build shells; needs foundations and framing calcs.",
"k": "Business",
"kc": 1
},
{
"n": "Blue Creek Construction",
"v": "General Contractor",
"c": "Post Falls",
"st": "ID",
"p": "(208) 555-1028",
"w": "https://www.example.com/bluecreekconstruct",
"e": "info@bluecreekconstruct.example.com",
"f": "",
"note": "Tilt-up and pre-engineered metal.",
"k": "Business",
"kc": 1
},
{
"n": "Prairie Gate Contracting",
"v": "General Contractor",
"c": "Rathdrum",
"st": "ID",
"p": "(208) 555-1035",
"w": "https://www.example.com/prairiegatecontrac",
"e": "info@prairiegatecontrac.example.com",
"f": "",
"note": "Agricultural and light industrial.",
"k": "Business",
"kc": 1
},
{
"n": "Northwood Civil Group",
"v": "Civil Engineering",
"c": "Hayden",
"st": "ID",
"p": "(208) 555-1042",
"w": "https://www.example.com/northwoodcivilgrou",
"e": "info@northwoodcivilgrou.example.com",
"f": "",
"note": "Site civil. Subs structural out on every job.",
"k": "Business",
"kc": 0
},
{
"n": "Timberline Surveying",
"v": "Land Surveying",
"c": "Coeur d'Alene",
"st": "ID",
"p": "(208) 555-1049",
"w": "https://www.example.com/timberlinesurveyin",
"e": "info@timberlinesurveyin.example.com",
"f": "",
"note": "Boundary and topo. Frequent referral source.",
"k": "Business",
"kc": 0
},
{
"n": "Harbor Point Development",
"v": "Developer",
"c": "Coeur d'Alene",
"st": "ID",
"p": "(208) 555-1056",
"w": "https://www.example.com/harborpointdevelop",
"e": "info@harborpointdevelop.example.com",
"f": "",
"note": "Waterfront multifamily. Long approval cycles.",
"k": "Business",
"kc": 0
},
{
"n": "Granite Peak Properties",
"v": "Developer",
"c": "Post Falls",
"st": "ID",
"p": "(208) 555-1063",
"w": "https://www.example.com/granitepeakpropert",
"e": "info@granitepeakpropert.example.com",
"f": "",
"note": "Light industrial park, phased.",
"k": "Business",
"kc": 0
},
{
"n": "Selkirk Steel Fabrication",
"v": "Steel Fabricator",
"c": "Ponderay",
"st": "ID",
"p": "(208) 555-1070",
"w": "https://www.example.com/selkirksteelfabric",
"e": "info@selkirksteelfabric.example.com",
"f": "",
"note": "Shop drawings and connection design.",
"k": "Business",
"kc": 0
},
{
"n": "Riverbend Precast",
"v": "Precast Concrete",
"c": "Spokane Valley",
"st": "WA",
"p": "(208) 555-1077",
"w": "https://www.example.com/riverbendprecast",
"e": "info@riverbendprecast.example.com",
"f": "",
"note": "Panels and stairs; needs erection engineering.",
"k": "Business",
"kc": 0
},
{
"n": "Coeur Millwork",
"v": "Millwork",
"c": "Hayden",
"st": "ID",
"p": "(208) 555-1084",
"w": "https://www.example.com/coeurmillwork",
"e": "info@coeurmillwork.example.com",
"f": "",
"note": "Commercial casework.",
"k": "Business",
"kc": 0
},
{
"n": "Lakeshore Mechanical",
"v": "Mechanical Contractor",
"c": "Coeur d'Alene",
"st": "ID",
"p": "(208) 555-1091",
"w": "https://www.example.com/lakeshoremechanica",
"e": "info@lakeshoremechanica.example.com",
"f": "",
"note": "Rooftop units — asks for framing checks.",
"k": "Business",
"kc": 0
},
{
"n": "Panhandle Electric Works",
"v": "Electrical Contractor",
"c": "Post Falls",
"st": "ID",
"p": "(208) 555-1098",
"w": "https://www.example.com/panhandleelectricw",
"e": "info@panhandleelectricw.example.com",
"f": "",
"note": "Service upgrades in older buildings.",
"k": "Business",
"kc": 0
},
{
"n": "Summit Roofing Systems",
"v": "Roofing",
"c": "Rathdrum",
"st": "ID",
"p": "(208) 555-1105",
"w": "https://www.example.com/summitroofingsyste",
"e": "info@summitroofingsyste.example.com",
"f": "",
"note": "Re-roofs that trigger snow-load review.",
"k": "Business",
"kc": 0
},
{
"n": "Whitetail Property Group",
"v": "Property Management",
"c": "Coeur d'Alene",
"st": "ID",
"p": "(208) 555-1112",
"w": "https://www.example.com/whitetailpropertyg",
"e": "info@whitetailpropertyg.example.com",
"f": "",
"note": "Owns eleven commercial buildings.",
"k": "Business",
"kc": 0
},
{
"n": "Kootenai Storage Partners",
"v": "Self Storage",
"c": "Post Falls",
"st": "ID",
"p": "(208) 555-1119",
"w": "https://www.example.com/kootenaistoragepar",
"e": "info@kootenaistoragepar.example.com",
"f": "",
"note": "Expanding; needs foundation design.",
"k": "Business",
"kc": 0
},
{
"n": "Pine Hollow Senior Living",
"v": "Senior Living",
"c": "Hayden",
"st": "ID",
"p": "(208) 555-1126",
"w": "https://www.example.com/pinehollowseniorli",
"e": "info@pinehollowseniorli.example.com",
"f": "",
"note": "Renovation with occupancy change.",
"k": "Business",
"kc": 0
},
{
"n": "St. Aloysius Academy",
"v": "Private School",
"c": "Coeur d'Alene",
"st": "ID",
"p": "(208) 555-1133",
"w": "https://www.example.com/staloysiusacademy",
"e": "info@staloysiusacademy.example.com",
"f": "",
"note": "Gym addition under discussion.",
"k": "Business",
"kc": 0
},
{
"n": "Northern Lakes Fire District",
"v": "Fire District",
"c": "Rathdrum",
"st": "ID",
"p": "(208) 555-1140",
"w": "https://www.example.com/northernlakesfired",
"e": "info@northernlakesfired.example.com",
"f": "",
"note": "Station remodel; public bid.",
"k": "Business",
"kc": 0
},
{
"n": "Silverwood Hospitality Group",
"v": "Hospitality",
"c": "Athol",
"st": "ID",
"p": "(208) 555-1147",
"w": "https://www.example.com/silverwoodhospital",
"e": "info@silverwoodhospital.example.com",
"f": "",
"note": "Two hotels, seasonal work.",
"k": "Business",
"kc": 0
},
{
"n": "Copper Basin Mining Services",
"v": "Industrial",
"c": "Kellogg",
"st": "ID",
"p": "(208) 555-1154",
"w": "https://www.example.com/copperbasinminings",
"e": "info@copperbasinminings.example.com",
"f": "",
"note": "Conveyor and headframe structures.",
"k": "Business",
"kc": 0
},
{
"n": "Clark Fork Timber",
"v": "Industrial",
"c": "Clark Fork",
"st": "ID",
"p": "(208) 555-1161",
"w": "https://www.example.com/clarkforktimber",
"e": "info@clarkforktimber.example.com",
"f": "",
"note": "Mill equipment platforms.",
"k": "Business",
"kc": 0
},
{
"n": "Spokane River Marine",
"v": "Marine",
"c": "Post Falls",
"st": "ID",
"p": "(208) 555-1168",
"w": "https://www.example.com/spokanerivermarine",
"e": "info@spokanerivermarine.example.com",
"f": "",
"note": "Docks and pile-supported structures.",
"k": "Business",
"kc": 0
},
{
"n": "Aspen Grove Homes",
"v": "Residential Builder",
"c": "Hayden",
"st": "ID",
"p": "(208) 555-1175",
"w": "https://www.example.com/aspengrovehomes",
"e": "info@aspengrovehomes.example.com",
"f": "",
"note": "Custom homes on steep lots.",
"k": "Business",
"kc": 0
},
{
"n": "Bitterroot Engineering Supply",
"v": "Supplier",
"c": "Coeur d'Alene",
"st": "ID",
"p": "(208) 555-1182",
"w": "https://www.example.com/bitterrootengineer",
"e": "info@bitterrootengineer.example.com",
"f": "",
"note": "Anchors and fasteners rep.",
"k": "Business",
"kc": 0
},
{
"n": "Trestle Creek Insurance",
"v": "Professional Services",
"c": "Sandpoint",
"st": "ID",
"p": "(208) 555-1189",
"w": "https://www.example.com/trestlecreekinsura",
"e": "info@trestlecreekinsura.example.com",
"f": "",
"note": "Carries the firm's professional liability.",
"k": "Business",
"kc": 0
}
];
